server:
  port: 8484

spring:
  application:
    name: myregistry
myregistry:
  serverList:
    - http://localhost:8484
    - http://localhost:8485
    - http://localhost:8486
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.flhai: DEBUG

